config/routes.rb
Rails.application.routes.draw do

  root 'application#delegator'

  # Session routes
  post 'login' => 'application#new_session', as: :login
  get 'logout' => 'application#destroy_session', as: :logout

  resources :w_transactions
  resources :pockets
  resources :users
end

app/models/pocket.rb
class Pocket < ActiveRecord::Base
  belongs_to :user
  has_many :transactions
end

app/models/user.rb
# Model: User
# Table: users
# Columns: 
#   t.string   "name"
#   t.string   "email"
#   t.string   "password_salt"
#   t.string   "password_salted"
#   t.datetime "created_at"
#   t.datetime "updated_at"
#
class User < ActiveRecord::Base
  before_save :encrypt

  has_one :pocket

  # validates :password_hash, precence: true, on: :update
  # validates :password, presence: true, on: :create

  attr_accessor :password

  def encrypt
    return unless password.present?
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_salted = BCrypt::Engine.hash_secret(password, password_salt)
  end
end

app/models/w_transaction.rb
class WTransaction < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :check_session, except: [:delegator, :new_session]

  def delegator
    if session[:user_id]
      redirect_to users_path
    else
      render :login, layout: false
    end
  end

  def new_session
    user = User.find_by_email(params[:email])
    if user
      hash = BCrypt::Engine.hash_secret(params[:password],user.password_salt)
      session[:user_id] = user.id if user.password_salted == hash
    end
    redirect_to root_path
  end

  def destroy_session
    reset_session
    redirect_to root_path
  end

  def check_session
    # return if controller_name == 'application'
    redirect_to root_path unless current_user
  end 

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
      
end   
      
      
      

app/controllers/pockets_controller.rb
class PocketsController < ApplicationController
  before_action :set_pocket, only: [:show, :edit, :update, :destroy]

  # GET /pockets
  # GET /pockets.json
  def index
    @pockets = Pocket.all
  end

  # GET /pockets/1
  # GET /pockets/1.json
  def show
  end

  # GET /pockets/new
  def new
    @pocket = Pocket.new
  end

  # GET /pockets/1/edit
  def edit
  end

  # POST /pockets
  # POST /pockets.json
  def create
    @pocket = Pocket.new(pocket_params)

    respond_to do |format|
      if @pocket.save
        format.html { redirect_to @pocket, notice: 'Pocket was successfully created.' }
        format.json { render :show, status: :created, location: @pocket }
      else
        format.html { render :new }
        format.json { render json: @pocket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pockets/1
  # PATCH/PUT /pockets/1.json
  def update
    respond_to do |format|
      if @pocket.update(pocket_params)
        format.html { redirect_to @pocket, notice: 'Pocket was successfully updated.' }
        format.json { render :show, status: :ok, location: @pocket }
      else
        format.html { render :edit }
        format.json { render json: @pocket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pockets/1
  # DELETE /pockets/1.json
  def destroy
    @pocket.destroy
    respond_to do |format|
      format.html { redirect_to pockets_url, notice: 'Pocket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pocket
      @pocket = Pocket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pocket_params
      params.require(:pocket).permit(:user_id, :balance)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password_salt, :password_salted)
    end
end

app/controllers/w_transactions_controller.rb
class WTransactionsController < ApplicationController
  before_action :set_w_transaction, only: [:show, :edit, :update, :destroy]

  # GET /w_transactions
  # GET /w_transactions.json
  def index
    @w_transactions = WTransaction.all
  end

  # GET /w_transactions/1
  # GET /w_transactions/1.json
  def show
  end

  # GET /w_transactions/new
  def new
    @w_transaction = WTransaction.new
  end

  # GET /w_transactions/1/edit
  def edit
  end

  # POST /w_transactions
  # POST /w_transactions.json
  def create
    @w_transaction = WTransaction.new(w_transaction_params)

    respond_to do |format|
      if @w_transaction.save
        format.html { redirect_to @w_transaction, notice: 'W transaction was successfully created.' }
        format.json { render :show, status: :created, location: @w_transaction }
      else
        format.html { render :new }
        format.json { render json: @w_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /w_transactions/1
  # PATCH/PUT /w_transactions/1.json
  def update
    respond_to do |format|
      if @w_transaction.update(w_transaction_params)
        format.html { redirect_to @w_transaction, notice: 'W transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @w_transaction }
      else
        format.html { render :edit }
        format.json { render json: @w_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /w_transactions/1
  # DELETE /w_transactions/1.json
  def destroy
    @w_transaction.destroy
    respond_to do |format|
      format.html { redirect_to w_transactions_url, notice: 'W transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_w_transaction
      @w_transaction = WTransaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def w_transaction_params
      params.require(:w_transaction).permit(:pocket_id, :amount, :tipo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pockets_helper.rb
module PocketsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/w_transactions_helper.rb
module WTransactionsHelper
end

app/views/application/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wallet" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="container">
      <%= form_tag(login_path, class: 'form-signin', role: 'form') do %>
        <h2 class="form-signin-heading">My Wallet</h2>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input name="email" type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
        <label for="inputPassword" class="sr-only">Password</label>
        <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <% end %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wallet" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Wallet</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Users", users_path  %></li>
            <li><%= link_to "Pockets", pockets_path  %></li>
            <li><%= link_to "Transactions", w_transactions_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pockets/_form.html.erb
<%= form_for @pocket, :html => { :class => "form-horizontal pocket" } do |f| %>

    <% if @pocket.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@pocket.errors.count, "error") %> prohibited this pocket from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @pocket.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%= error_span(@pocket[:user_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :balance, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :balance, :class => 'form-control' %>
    </div>
    <%= error_span(@pocket[:balance]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            pockets_path, :class => 'btn btn-default' %>

<% end %>

app/views/pockets/edit.html.erb
<%- model_class = Pocket -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pockets/index.html.erb
<%- model_class = Pocket -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:balance) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pockets.each do |pocket| %>
      <tr>
        <td><%= link_to pocket.id, pocket_path(pocket) %></td>
        <td><%= pocket.user_id %></td>
        <td><%= pocket.balance %></td>
        <td><%=l pocket.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_pocket_path(pocket), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      pocket_path(pocket),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_pocket_path,
            :class => 'btn btn-primary' %>

app/views/pockets/new.html.erb
<%- model_class = Pocket -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pockets/show.html.erb
<%- model_class = Pocket -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @pocket.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:balance) %>:</strong></dt>
  <dd><%= @pocket.balance %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              pockets_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_pocket_path(@pocket), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              pocket_path(@pocket),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/transactions/edit.html.erb
<%- model_class = Transaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/transactions/index.html.erb
<%- model_class = Transaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:pocket_id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= link_to transaction.id, transaction_path(transaction) %></td>
        <td><%= transaction.pocket_id %></td>
        <td><%= transaction.description %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.type %></td>
        <td><%=l transaction.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_transaction_path(transaction), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      transaction_path(transaction),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_transaction_path,
            :class => 'btn btn-primary' %>

app/views/transactions/new.html.erb
<%- model_class = Transaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/transactions/show.html.erb
<%- model_class = Transaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:pocket_id) %>:</strong></dt>
  <dd><%= @transaction.pocket_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @transaction.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @transaction.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
  <dd><%= @transaction.type %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              transactions_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_transaction_path(@transaction), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              transaction_path(@transaction),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

    <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:email]) %>
  </div>
  <div class="control-group">
    <%= f.label :password_salt, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :password_salt, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:password_salt]) %>
  </div>
  <div class="control-group">
    <%= f.label :password_salted, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :password_salted, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:password_salted]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            users_path, :class => 'btn btn-default' %>

<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:password_salt) %></th>
      <th><%= model_class.human_attribute_name(:password_salted) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_salt %></td>
        <td><%= user.password_salted %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/w_transactions/edit.html.erb
<%- model_class = WTransaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/w_transactions/index.html.erb
<%- model_class = WTransaction -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:pocket_id) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:tipo) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @w_transactions.each do |w_transaction| %>
      <tr>
        <td><%= link_to w_transaction.id, w_transaction_path(w_transaction) %></td>
        <td><%= w_transaction.pocket_id %></td>
        <td><%= w_transaction.amount %></td>
        <td><%= w_transaction.tipo %></td>
        <td><%=l w_transaction.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_w_transaction_path(w_transaction), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      w_transaction_path(w_transaction),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_w_transaction_path,
            :class => 'btn btn-primary' %>